Alojat/Controllers/HomeController.cs
using Alojat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Alojat.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Alojat/Controllers/InmuebleController.cs
using Alojat.interfa;
using Alojat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace Alojat.Controllers
{
    public class InmuebleController : Controller
    {
        private readonly IInmueble mInmueble;
        private readonly IUsuario mUsuario;
        private readonly IUserClaim mClaim;
        private readonly IReferencia mReferencia;
        private readonly IVinmueble mValidate;
        private readonly ISha mSha;

        public InmuebleController(IInmueble mInmueble, IUsuario mUsuario, IUserClaim mClaim, IReferencia mReferencia, IVinmueble mValidate, ISha mSha)
        {
            this.mInmueble = mInmueble;
            this.mUsuario = mUsuario;
            this.mClaim = mClaim;
            this.mReferencia = mReferencia;
            this.mValidate = mValidate;
            this.mSha = mSha;
        }

        [Authorize(Roles = "Admin,Propietario")]

        public IActionResult Index()
        {
            try
            {
                if (HttpContext.User.Identity is not ClaimsIdentity identity) return NotFound();

                var data = mClaim.GetUser(identity.Claims);

                var usuario = mUsuario.GetUsuarioRol(data.Email);

                if (usuario.Rol.DescripcionRol == "Admin")
                {
                    return View(mInmueble.ListInmueRefe());
                }

                return View(mInmueble.ListInmueRefeUsu(usuario.UsuarioID));
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin,Propietario")]
        public ViewResult Create()
        {
            ViewData["PuntoReferencia"] = new SelectList(mReferencia.LisReferencia(), "PuntoReferenciaID", "NombrePuntoReferencia");
            return View();
        }

        [Authorize(Roles = "Admin,Propietario")]
        [HttpPost]
        public async Task<IActionResult> Create(Inmueble inmueble, IFormFile Imagen)
        {
            try
            {
                if (HttpContext.User.Identity is not ClaimsIdentity identity) return NotFound();

                var data = mClaim.GetUser(identity.Claims);

                var usuario = mUsuario.FirstOr(data.Email);

                if (!mValidate.Validate(inmueble, ModelState))
                {
                    ViewData["PuntoReferencia"] = new SelectList(mReferencia.LisReferencia(), "PuntoReferenciaID", "NombrePuntoReferencia", inmueble.PuntoReferenciaID);
                    return View("Create", inmueble);
                }

                if (Imagen != null)
                {
                    Stream image = Imagen.OpenReadStream();

                    var urlimagen = await mSha.SubirStorage(image, Guid.NewGuid().ToString());
                    inmueble.ImagenInmueble = urlimagen;
                }

                inmueble.UsuarioID = usuario.UsuarioID;

                mInmueble.SaveInmueble(inmueble);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin,Propietario")]
        public IActionResult Details(int id)
        {
            try
            {
                var inmueble = mInmueble.FindInmu(id);

                ViewData["PuntoReferenciaID"] = new SelectList(mReferencia.LisReferencia(), "PuntoReferenciaID", "NombrePuntoReferencia", inmueble.PuntoReferenciaID);

                return View(inmueble);
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin,Propietario")]
        public IActionResult Delete(int id)
        {
            try
            {
                var inmueble = mInmueble.FindInmu(id);
                mInmueble.RemoveInmueble(inmueble);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin,Propietario")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Inmueble inmueble)
        {
            try
            {
                if (!mValidate.Validate(inmueble, ModelState))
                {
                    var inmueb = mInmueble.FindInmu(inmueble.InmuebleID);

                    ViewData["PuntoReferenciaID"] = new SelectList(mReferencia.LisReferencia(), "PuntoReferenciaID", "NombrePuntoReferencia", inmueble.PuntoReferenciaID);
                    return View("Details", inmueble);
                }

                mInmueble.UpdateInmueble(inmueble);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return NotFound();
            }
        }
    }
}

Alojat/Controllers/PuntoController.cs
using Alojat.interfa;
using Alojat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Alojat.Controllers
{
    public class PuntoController : Controller
    {
        private readonly IReferencia mReferencia;
        private readonly IVpunto mVpunto;

        public PuntoController(IReferencia mReferencia, IVpunto mVpunto)
        {
            this.mReferencia = mReferencia;
            this.mVpunto = mVpunto;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            try
            {
                return View(mReferencia.LisReferencia());
            }
            catch (Exception)
            {
                return NotFound();
            }

        }

        [Authorize(Roles = "Admin")]
        public IActionResult Details(int id)
        {
            try
            {
                var puntoReferencia = mReferencia.FirstPunto(id);

                return View(puntoReferencia);
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PuntoReferenciaID,NombrePuntoReferencia,DireccionReferencia,Latitud,Longitud")] PuntoReferencia puntoReferencia)
        {
            try
            {
                if (!mVpunto.Validate(puntoReferencia,ModelState))
                {
                    return View(puntoReferencia);
                }

                mReferencia.SavePunto(puntoReferencia);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            try
            {
                var puntoReferencia = mReferencia.FindPunto(id);

                return View(puntoReferencia);
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("PuntoReferenciaID,NombrePuntoReferencia,DireccionReferencia,Latitud,Longitud")] PuntoReferencia puntoReferencia)
        {
            try
            {
                if (!mVpunto.Validate(puntoReferencia, ModelState))
                {
                    return View("Edit", puntoReferencia);
                }

                mReferencia.UpdatePunto(puntoReferencia);
                return RedirectToAction(nameof(Index));
               
            }
            catch (Exception)
            {
                return NotFound();
            }
            
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            try{
                var puntoReferencia = mReferencia.FirstPunto(id);

                mReferencia.RemovePunto(puntoReferencia);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return NotFound();
            }

        }
    }
}

Alojat/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAlojat.cshtml";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
</div>

<div class="row">
    @if (User.IsInRole("Admin"))
    {
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                <div class="h5 mb-0 font-weight-bold text-gray-800">
                                    <a class="option-dashboard" asp-controller="Categoria" asp-action="Index">CATEGORIAS</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                                    <a class="option-dashboard" asp-controller="Usuario" asp-action="Index">USUARIOS</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                                        <a class="option-dashboard" asp-controller="Punto" asp-action="Index">PUNTOS</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    @if (User.IsInRole("Admin") || User.IsInRole("Propietario"))
    {
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                                    <a class="option-dashboard" asp-controller="Inmueble" asp-action="Index">INMUEBLES</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                                    <a class="option-dashboard" asp-controller="Servicio" asp-action="Index">SERVICIOS</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    }


    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="col-auto">
                            <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                                <a class="option-dashboard" asp-controller="Buscar" asp-action="Buscar">BUSCAR</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>