Alojat/Models/Servicio.cs
namespace Alojat.Models
{
    public class Servicio
    {
        public int ServicioID { get; set; }
        public string ImagenServicio { get; set; } = "https://firebasestorage.googleapis.com/v0/b/lobos-marinos.appspot.com/o/Alojat%2Fajojat.jpg?alt=media&token=d66534de-af0c-4ee7-8a34-d5652b657ffa";
        public string UbicacionPiso { get; set; } = "";
        public string DescripcionServicio { get; set; } = "";
        public string TipoServicio { get; set; } = "";
        public decimal Precio { get; set; } 
        public bool EstadoAlquilerServicio { get; set; }
        public int CategoriaID { get; set; }
        public Categoria? Categoria { get; set; }
        public int InmuebleID { get; set; }
        public Inmueble? Inmueble { get; set; }
    }
}

Alojat/Controllers/ServicioController.cs
using Alojat.interfa;
using Alojat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Alojat.Controllers
{
    public class ServicioController : Controller
    {
        private readonly IServicio mServicio;
        private readonly IUsuario mUsuario;
        private readonly IUserClaim mClaim;
        private readonly ICategoria mCategoria;
        private readonly IInmueble mInmueble;
        private readonly ISha mSha;
        private readonly IVservicio mValidate;

        public ServicioController(IServicio mServicio, IUsuario mUsuario, IUserClaim mClaim, ICategoria mCategoria, IInmueble mInmueble, ISha mSha, IVservicio mValidate)
        {
            this.mServicio = mServicio;
            this.mUsuario = mUsuario;
            this.mClaim = mClaim;
            this.mCategoria = mCategoria;
            this.mInmueble = mInmueble;
            this.mSha = mSha;
            this.mValidate = mValidate;
        }

        [Authorize(Roles = "Admin,Propietario")]
        public IActionResult Index()
        {
            try
            {
                if (HttpContext.User.Identity is not ClaimsIdentity identity) return NotFound();

                var data = mClaim.GetUser(identity.Claims);

                var usuario = mUsuario.GetUsuarioRol(data.Email);

                if (usuario.Rol.DescripcionRol == "Admin")
                {
                    return View(mServicio.ListGet());
                }

                return View(mServicio.ListGetUser(usuario.UsuarioID));
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin,Propietario")]
        public IActionResult Create()
        {
            try
            {
                if (HttpContext.User.Identity is not ClaimsIdentity identity) return NotFound();

                var data = mClaim.GetUser(identity.Claims);

                var usuario = mUsuario.GetUsuarioRol(data.Email);

                ViewData["CategoriaID"] = new SelectList(mCategoria.LisCategoria(), "CategoriaID", "NombreCategoria");

                if (usuario.Rol.DescripcionRol == "Admin")
                {
                    ViewData["InmuebleID"] = new SelectList(mInmueble.ListInmueRefe(), "InmuebleID", "DireccionInmueble");
                }
                else
                {
                    ViewData["InmuebleID"] = mInmueble.SelectLis(usuario.UsuarioID);
                }

                return View();
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin,Propietario")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Servicio servicio, IFormFile Imagen)
        {
            try
            {
                if (!mValidate.Validate(servicio, ModelState))
                {
                    ViewData["CategoriaID"] = new SelectList(mCategoria.LisCategoria(), "CategoriaID", "NombreCategoria", servicio.CategoriaID);
                    ViewData["InmuebleID"] = new SelectList(mInmueble.ListInmueRefe(), "InmuebleID", "DireccionInmueble");
                    return View(servicio);
                }

                if (Imagen != null)
                {
                    Stream image = Imagen.OpenReadStream();
                    var urlimagen = await mSha.SubirStorage(image, Guid.NewGuid().ToString());
                    servicio.ImagenServicio = urlimagen;
                }

                mServicio.SaveServicio(servicio);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin,Propietario")]
        public IActionResult Details(int id)
        {
            try
            {
                var servicio = mServicio.FirstOr(id);

                var cat = new SelectList(mCategoria.LisCategoria(), servicio.CategoriaID);
                var inm = mInmueble.SelectLis(servicio.InmuebleID);

                ViewData["CategoriaID"] = new SelectList(mCategoria.LisCategoria(), "CategoriaID", "NombreCategoria", servicio.CategoriaID);
                ViewData["InmuebleID"] = new SelectList(mInmueble.ListInmueRefe(), "InmuebleID", "DireccionInmueble", servicio.InmuebleID);

                return View(servicio);
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin,Propietario")]
        public IActionResult Delete(int id)
        {
            try
            {
                var servicio = mServicio.FirstOr(id);
                mServicio.DeleteServicio(servicio);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin,Propietario")]
        public IActionResult Edit(Servicio servicio)
        {
            try
            {
                if (!mValidate.Validate(servicio, ModelState))
                {
                    ViewData["CategoriaID"] = new SelectList(mCategoria.LisCategoria(), "CategoriaID", "NombreCategoria", servicio.CategoriaID);
                    ViewData["InmuebleID"] = new SelectList(mInmueble.ListInmueRefe(), "InmuebleID", "DireccionInmueble", servicio.InmuebleID);

                    return View("Details", servicio);
                }

                mServicio.UpdateServicio(servicio);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return NotFound();
            }
        }
    }
}

Alojat/Views/Servicio/Create.cshtml
@model Alojat.Models.Servicio
@{
    Layout = "~/Views/Shared/_LayoutAlojat.cshtml";
}

<div class="mt-0">
    <div class="card border-dark mb-3">
        <div class="card-header text-white bg-dark">
            <h3>Registro de Servicio</h3>
        </div>
        <div class="card-body">
            <form asp-action="Create" asp-controller="Servicio" method="POST" enctype="multipart/form-data">
                <button type="submit" class="btn btn-dark mb-3 mb-1">Registrar</button>
                <div class="row g-2">
                    <style>
                        .upload {
                            width: 100px;
                            position: relative;
                            margin: auto;
                        }

                            .upload .round {
                                position: absolute;
                                bottom: 0;
                                right: 0;
                                background: #00B4FF;
                                width: 32px;
                                height: 32px;
                                line-height: 33px;
                                text-align: center;
                                border-radius: 50%;
                                overflow: hidden;
                            }

                                .upload .round input[type = "file"] {
                                    position: absolute;
                                    transform: scale(2);
                                    opacity: 0;
                                }

                        input[type=file]::-webkit-file-upload-button {
                            cursor: pointer;
                        }

                    </style>
                    <div class="col-sm-6 col-md-6">
                        <div class="upload mb-3">
                            <img src="~/img/undraw_profile_1.svg" id="img" width=100 height=100 alt="">
                            <div class="round">
                                <input accept="image/" name="Imagen" id="foto" type="file" />
                                <i class="fa fa-camera" style="color: #fff;"></i>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Ubicación de Piso</label>
                            <input asp-for="UbicacionPiso" class="form-control" />
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Piso")</strong></p>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Descripción</label>
                            <textarea asp-for="DescripcionServicio" class="form-control"></textarea>
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Descrip")</strong></p>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Categoria</label>
                            <select asp-for="CategoriaID" class="form-control" asp-items="@ViewBag.CategoriaID"></select>
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Categoria")</strong></p>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="mb-3">
                            <label class="form-label">Tipo de servicio</label>
                            <input type="tel" asp-for="TipoServicio" class="form-control" />
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Tipo")</strong></p>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Precio</label>
                            <input name"Precio" class="form-control" />
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Precio")</strong></p>
                        </div>
                        <div class="mb-3">
                            <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" asp-for="EstadoAlquilerServicio" role="" id="flexSwitchCheckChecked" checked>
                                <label class="form-check-label" for="flexSwitchCheckChecked">Estado</label>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Inmueble</label>
                            <select asp-for="InmuebleID" class="form-control" asp-items="ViewBag.InmuebleID"></select>
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Inmueble")</strong></p>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    const file = document.getElementById('foto');
    const img = document.getElementById('img');
    file.addEventListener('change', e => {
        if (e.target.files[0]) {
            if (e.target.files[0].type == 'image/jpeg' | e.target.files[0].type == 'image/png' | e.target.files[0].type == 'image/jpg') {
                const reader = new FileReader();

                reader.onload = function (e) {
                    img.src = e.target.result;
                }

                reader.readAsDataURL(e.target.files[0])
            }
        } else {
            img.src = defaultFile;
        }
    });

</script>

Alojat/Views/Servicio/Details.cshtml
@model Alojat.Models.Servicio
@{
    Layout = "~/Views/Shared/_LayoutAlojat.cshtml";
}

<div class="mt-0">
    <div class="card border-dark mb-3">
        <div class="card-header text-white bg-dark">
            <h3>Detalle de Servicio</h3>
        </div>
        <h5>@ViewBag.image</h5>

        <div class="card-body">
            <form asp-action="Edit" enctype="multipart/form-data">
                <button type="submit" class="btn btn-dark mb-3 mb-1">Actualizar</button>
                <div class="row g-2">
                    <style>
                        .upload {
                            width: 100px;
                            position: relative;
                            margin: auto;
                        }

                            .upload .round {
                                position: absolute;
                                bottom: 0;
                                right: 0;
                                background: #00B4FF;
                                width: 32px;
                                height: 32px;
                                line-height: 33px;
                                text-align: center;
                                border-radius: 50%;
                                overflow: hidden;
                            }

                                .upload .round input[type = "file"] {
                                    position: absolute;
                                    transform: scale(2);
                                    opacity: 0;
                                }

                        input[type=file]::-webkit-file-upload-button {
                            cursor: pointer;
                        }

                    </style>
                    <div class="col-sm-6 col-md-6">
                        <div class="upload mb-3">
                            <img src="@Url.Content(Model.ImagenServicio)" id="img" width=150 height=150 alt="">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Ubicación de Piso</label>
                            <input asp-for="UbicacionPiso" class="form-control" />
                            <input hidden asp-for="ServicioID" class="form-control" />
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Ubicacion")</strong></p>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Descripción</label>
                            <textarea asp-for="DescripcionServicio" class="form-control"></textarea>
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Descripcion")</strong></p>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Categoria</label>
                            <select asp-for="CategoriaID" class="form-control" asp-items="@ViewBag.CategoriaID"></select>
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Categoria")</strong></p>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="mb-3">
                            <label class="form-label">Tipo de servicio</label>
                            <input type="tel" asp-for="TipoServicio" class="form-control" />
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Tipo")</strong></p>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Precio</label>
                            <input asp-for="Precio" class="form-control" />
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Precio")</strong></p>
                        </div>
                        <div class="mb-3">
                            <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" asp-for="EstadoAlquilerServicio" role="" id="flexSwitchCheckChecked">
                                <label class="form-check-label" for="flexSwitchCheckChecked">Estado</label>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Inmueble</label>
                            <select asp-for="InmuebleID" class="form-control" asp-items="@ViewBag.InmuebleID"></select>
                            <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Inmueble")</strong></p>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div id="mapa" style="width:100%; height:500px;"></div>
    </div>
</div>

<script>
    const file = document.getElementById('latitud').value;
    const img = document.getElementById('longitud').value;


    function iniciarMapa() {
        var latitud = file;
        var longitud = img

        coordenas = {
            lng: longitud,
            lat: latitud
        }

        generarMapa(coordenas)
    }

    function generarMapa(coordenas) {
        var mapa = new google.maps.Map(document.getElementById('mapa'),
            {
                zoom: 14,
                center: new google.maps.LatLng(coordenas.lat, coordenas.lng)
            });

        marcador = new google.maps.Marker({
            map: mapa,
            draggable: true,
            position: new google.maps.LatLng(coordenas.lat, coordenas.lng)
        });

        marcador.addListener('dragend', function (event) {
            document.getElementById("latitud").value = this.getPosition().lat();
            document.getElementById("longitud").value = this.getPosition().lng();
        })
    }
</script>

Alojat/Views/Servicio/Index.cshtml
@model IEnumerable<Alojat.Models.Servicio>
@{
    Layout = "~/Views/Shared/_LayoutAlojat.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3 ">
        <div class="row">
            <div class="col-md-6 text-center">
                <h6 class="m-0 font-weight-bold text-primary mt-3">Servicios</h6>
            </div>
            <div class="col-md-6 text-center">
                <a asp-controller="Servicio" asp-action="Create" class="btn btn-primary mt-2">
                    <i class="fas fa-plus"></i>
                </a>
            </div>
        </div>


    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Ubicación</th>
                        <th>Tipo</th>
                        <th>Precio</th>
                        <th>Estado</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Piso</th>
                        <th>Tipo</th>
                        <th>Precio</th>
                        <th>Estado</th>
                        <th>Opciones</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UbicacionPiso)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TipoServicio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Precio)
                            </td>

                            @if (@item.EstadoAlquilerServicio)
                            {
                                <td>Activado</td>
                            }
                            else
                            {
                                <td>Desactivado</td>
                            }

                            <td>
                                <a class="fas fa-eye" title="Detalle" asp-action="Details" asp-route-id="@item.ServicioID"></a> |
                                <a class="fas fa-delete"
                               style="cursor:pointer"
                               data-toggle="modal"
                               data-target="#del-@item.ServicioID">
                                    <i class="fa-sharp fa-solid fa-trash" style="color:red;"></i>
                                </a>
                                <div class="modal fade" id="del-@item.ServicioID" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                 aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">¿Estas seguro?</h5>
                                                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">¡No podrás revertir esto!</div>
                                            <div class="modal-footer">
                                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                                                <a class="btn btn-primary"
                                               asp-action="Delete"
                                               asp-route-id="@item.ServicioID">
                                                    Eliminar
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>