Alojat/Models/Categoria.cs
namespace Alojat.Models
{
    public class Categoria
    {
        public int CategoriaID { get; set; }
        public string NombreCategoria { get; set; } = "";
        public ICollection<Servicio>? Servicios { get; set; }
    }
}

Alojat/Controllers/CategoriaController.cs
using Alojat.interfa;
using Alojat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Alojat.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ICategoria mCategoria;
        private readonly IVcategoria mVcategoria;

        public CategoriaController(ICategoria mCategoria, IVcategoria mVcategoria)
        {
            this.mCategoria = mCategoria;
            this.mVcategoria = mVcategoria;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(mCategoria.LisCategoria());
        }

        [Authorize(Roles = "Admin")]
        public ViewResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("CategoriaID,NombreCategoria")] Categoria categoria)
        {
            if (!mVcategoria.Validate(categoria,ModelState))
            {
                return View(categoria);
            }

            mCategoria.SaveCategoria(categoria);
            return RedirectToAction(nameof(Index));

        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            if (!mCategoria.ValidateCategoria(id))
            {
                return NotFound();
            }

            var categoria = mCategoria.FindCategoria(id);

            if (categoria == null)
            {
                return NotFound();

            }

            return View(categoria);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("CategoriaID,NombreCategoria")] Categoria categoria)
        {
            if (id != categoria.CategoriaID)
            {
                return NotFound();
            }

            if (!mVcategoria.UpdateCate(categoria, ModelState))
            {
                return View("Edit", categoria);
            }

            mCategoria.UpdateCategoria(categoria);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            if (!mCategoria.ValidateCategoria(id))
            {
                return NotFound();
            }

            var categoria = mCategoria.FirstCategoria(id);
            mCategoria.RemoveCategoria(categoria);

            return RedirectToAction(nameof(Index));
        }
    }
}

Alojat/Views/Categoria/Create.cshtml
@model Alojat.Models.Categoria
@{
    Layout = "~/Views/Shared/_LayoutAlojat.cshtml";
}

<div class="card o-hidden border-0 shadow-lg">
    <div class="card-body p-0">
        <div class="row">
            <div class="col-lg-12">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-1">Crear categoria</h1>
                    </div>
                    <form class="user" asp-action="Create">
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <label asp-for="NombreCategoria" class="control-label"></label>
                                <input asp-for="NombreCategoria" class="form-control" />
                                <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Categ")</strong></p>
                                <input type="submit" value="Crear" class="btn btn-primary btn-user btn-block mt-4"/>
                            </div>

                        </div>
                        <hr>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Alojat/Views/Categoria/Edit.cshtml
@model Alojat.Models.Categoria

@{
    Layout = "~/Views/Shared/_LayoutAlojat.cshtml";
}

<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <div class="row">
            <div class="col-lg-12">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Editar categoría</h1>
                    </div>
                    <form class="user" asp-action="Edit">
                        <input type="hidden" asp-for="CategoriaID" />
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <label asp-for="NombreCategoria" class="control-label"></label>
                                <input asp-for="NombreCategoria" class="form-control" />
                                <p><strong style="color:red; font-size:14px">@Html.ValidationMessage("Categ")</strong></p>
                                <input type="submit" value="Actualizar" class="btn btn-primary btn-user btn-block mt-4"/>
                            </div>
                        </div>
                        <hr>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Alojat/Views/Categoria/Index.cshtml
@model IEnumerable<Alojat.Models.Categoria>
@{
    Layout = "~/Views/Shared/_LayoutAlojat.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3 ">
        <div class="row">
            <div class="col-md-6 text-center">
                <h6 class="m-0 font-weight-bold text-primary mt-3">Categorias</h6>
            </div>
            <div class="col-md-6 text-center">
                <a asp-controller="Categoria" asp-action="Create" class="btn btn-primary mt-2">
                    <i class="fas fa-plus"></i>
                </a>
            </div>
        </div>


    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Categoria</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>CategoriaID</th>
                        <th>Categoria</th>
                        <th>Opciones</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CategoriaID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NombreCategoria)
                            </td>
                            <td>
                                <a class="fas fa-edit" title="Editar" asp-action="Edit" asp-route-id="@item.CategoriaID"></a> |
                                <a class="fas fa-delete"
                               data-toggle="modal"
                               data-target="#del-@item.CategoriaID">
                                    <i class="fa-sharp fa-solid fa-trash" style="color:red;"></i>
                                </a>

                                <div class="modal fade" id="del-@item.CategoriaID" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                 aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">¿Estas seguro?</h5>
                                                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">¡No podrás revertir esto!</div>
                                            <div class="modal-footer">
                                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                                                <a class="btn btn-primary"
                                                asp-action="Delete"
                                                asp-route-id="@item.CategoriaID">
                                                    Eliminar
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>